# import tests to run within this module
from localground.apps.site.api.tests.admin_tests import *
from localground.apps.site.api.tests.association_tests import *
from localground.apps.site.api.tests.audio_tests import *
from localground.apps.site.api.tests.form_tests import *
from localground.apps.site.api.tests.field_tests import *
from localground.apps.site.api.tests.homepage_tests import *
from localground.apps.site.api.tests.layer_tests import *
from localground.apps.site.api.tests.marker_tests import *
from localground.apps.site.api.tests.markerwattrs_tests import *
from localground.apps.site.api.tests.print_tests import *
from localground.apps.site.api.tests.project_tests import *
from localground.apps.site.api.tests.photo_tests import *
from localground.apps.site.api.tests.renderer_tests import *
from localground.apps.site.api.tests.map_tests import *
from localground.apps.site.api.tests.mapimage_tests import *
from localground.apps.site.api.tests.sql_parse_tests import *
from localground.apps.site.api.tests.tags_tests import *
from localground.apps.site.api.tests.sharing_tests import *
from localground.apps.site.api.tests.user_profile_tests import *
from localground.apps.site.api.tests.video_tests import *
from localground.apps.site.api.tests.icon_tests import *
